let denbor = 50
basic.forever(function () {
    led.plot(0, 0)
    basic.pause(denbor)
    led.plot(0, 1)
    basic.pause(denbor)
    led.plot(0, 2)
    basic.pause(denbor)
    led.plot(0, 3)
    basic.pause(denbor)
    led.plot(0, 4)
    basic.pause(denbor)
    led.plot(1, 4)
    basic.pause(denbor)
    led.plot(2, 4)
    basic.pause(denbor)
    led.plot(3, 4)
    basic.pause(denbor)
    led.plot(4, 4)
    basic.pause(denbor)
    led.plot(4, 3)
    basic.pause(denbor)
    led.plot(4, 2)
    basic.pause(denbor)
    led.plot(4, 2)
    basic.pause(denbor)
    led.plot(4, 1)
    basic.pause(denbor)
    led.plot(4, 0)
    basic.pause(denbor)
    led.plot(3, 0)
    basic.pause(denbor)
    led.plot(2, 0)
    basic.pause(denbor)
    led.plot(1, 4)
    basic.pause(denbor)
    led.plot(1, 0)
    basic.pause(denbor)
    led.unplot(0, 0)
    basic.pause(denbor)
    led.unplot(0, 1)
    basic.pause(denbor)
    led.unplot(0, 2)
    basic.pause(denbor)
    led.unplot(0, 4)
    basic.pause(denbor)
    led.unplot(1, 4)
    basic.pause(denbor)
    led.unplot(2, 4)
    basic.pause(denbor)
    led.unplot(3, 4)
    basic.pause(denbor)
    led.unplot(4, 4)
    basic.pause(denbor)
    led.unplot(4, 3)
    basic.pause(denbor)
    led.unplot(4, 2)
    basic.pause(denbor)
    led.unplot(4, 1)
    basic.pause(denbor)
    led.unplot(4, 0)
    basic.pause(denbor)
    led.unplot(3, 0)
    basic.pause(denbor)
    led.unplot(2, 0)
    basic.pause(denbor)
    led.unplot(1, 0)
    basic.pause(denbor)
    led.unplot(1, 0)
    basic.pause(denbor)
    led.unplot(0, 3)
    basic.pause(denbor)
})
